language: node_js
node_js:
  - "node"

before_script:
  - npm ci

script:
  - npm run cibuild

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    repo: varianter/handbook-host
    target_branch: master
    fqdn: handbook.variant.no
  - provider: npm
    email: mikaelbre@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
